name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Build, run, test and push the Docker image
      run: |
            docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/predictor-api:latest
            docker run -d -p 8000:8000 ${{secrets.DOCKER_USERNAME}}/predictor-api:latest
            
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v3
      with:
        path: "app/test-requirements.txt"
    - name: Run tests with pytest
      run: pytest 
    - name: Push to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/predictor-api:latest
      
    

      
    
  
    
