name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build, run, test and push the Docker image
      run: |
            docker build . --file Dockerfile --tag predictor-api:latest
            docker run --network ${{ job.container.network }} -d -p 8000:8000 prediction-api
            
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    - name: Run tests with pytest
      run: pytest 
    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/predictor-api:tagname
      
    

      
    
  
    
